### ISSUE TITLE
Cannot Train In Heavy Mageweave Bandage

### ISSUE THREAD

**Issue by UtopiaPC** [elysium-project/bug-tracker#261]
![firstaid](https://user-images.githubusercontent.com/35043531/34498791-2ddd87ae-efd1-11e7-9467-7c1c86c01a73.jpg)

As you can see in the picture, I have completed the [Triage] quest and my maximum skill level is now 300. I am currently at 250 skill level, 10 higher than the required 240 to learn Heavy Mageweave Bandage. 

I have tried to dezone and rezone and also log out and back on to see if it would correct the bug, neither has worked.

**Comment by totokadoba** [comment]
Having the same problem. I have leveled my first aid all the way to 270 til mageweave bandages are gray. He sould have offered me heavy mageweave bandages at 240 and runecloth bandages at 260 but there is no option for it.

**Comment by UtopiaPC** [comment]
My girlfriend is also having the same problem. We did the TRIAGE quest one after another and neither of us can upgrade to Heavy Mageweave.

**Comment by Terranzin** [comment]
I´ve reviewed your issue and manage to reproduce the same error. +1 for the picture

**Comment by rubenjpneves** [comment]
Same problem, 241 first aid but can't learn heavy mageweave bandage. I'm on the horde side.

**Comment by totokadoba** [comment]
Just tried again and was able to learn both heavy mageweave and runecloth bandaged. 

thx

**Comment by gricen** [comment]
Yes I am on the Horde side and tried to repeat the quest but after doing what the GM instructed me to do I cant even take the quest again as it still comes up as being completed. So have ditched the quest and cleared my WDB folder again. Waiting on an in game ticket for help

**Comment by DreadedWarlock** [comment]
I am having this issue as well :(

**Comment by gricen** [comment]
Well I managed to do the quest again today after I ditched it, logged out, cleared the WDB folder and logged back it. Started the quested again and all is good :)

**Comment by DreadedWarlock** [comment]
Thank you Rain for helping me with the Mageweave Bandage but I still can't train either Runecloth and Heavy Runecloth Bandages :(

**Comment by Egregious** [comment]
Looks like this issue should be fixed.

**Comment by Macsimka** [comment]
Fixed.

**Comment by fier11** [comment]
![bandages](https://user-images.githubusercontent.com/34729389/38230079-c62ee16e-36d1-11e8-92a8-070b7e5486e9.png)

April 2nd, 2018 - Still broken... at least on Horde side.

**Comment by fier11** [comment]
Nvm. GM told me you have to be level 40 to learn Heavy Mageweave Bandages.
