### ISSUE TITLE
Can't learn a leatherworking recipe

### ISSUE THREAD

**Issue by paga90** [elysium-project/bug-tracker#288]
Hi,
I'm lvl 45 artisan tribal leatherworker (300/300) and i can't learn the recipe for [devilsaur leggins](http://db.vanillagaming.org/?item=15772). The requirements are met, but the error says "You do not have a required proficiency for that item", still i get the animation of something being crafted. Please help.

Gnoos, gnome rogue

**Comment by fulzamoth** [comment]
This is a dupe of #212

**Comment by Pikseh** [comment]
It is not, since the problem was different at that point, or rather, back then it said it required dragonscale leatherworking. Now it states that it requires tribal, but in reality is STILL requires dragonscale (or something else). If anything it is a dupe of my post #280

**Comment by Terranzin** [comment]
Pikseh, Have you attempted contacting our GM team ingame? The issue isn´t reproducable on our PTR, maybe you need to clear your WDB folder or something similar for the client to understand there´s changes?

**Comment by cheese42069** [comment]
I've also had this issue and have tried clearing the WDB folder but the problem remains. I've also contacted a GM ingame who then told me to ask on the bug tracker.

**Comment by fulzamoth** [comment]
#280 has been confirmed. #212 was only half fixed - the display is correct, the spec link is still wrong.

**Comment by twink** [comment]
Fixed.

**Comment by paga90** [comment]
![default](https://user-images.githubusercontent.com/32129260/34918989-96b9308e-f954-11e7-803a-91c32eb8fd88.png)
Still not working =(

**Comment by paga90** [comment]
![default](https://user-images.githubusercontent.com/32129260/34919005-ce8dabfc-f954-11e7-8581-ce3eb6e081d3.png)
Still not working

**Comment by twink** [comment]
@paga90 wait for server update. It's was fixed, but not applied.

**Comment by paga90** [comment]
Thank you very much! All working correctly right now.
