### ISSUE TITLE
Blood Craze Fury Warriors Talent

### ISSUE THREAD

**Issue by wmuadib** [elysium-project/bug-tracker#757]
Hello, I noticed today that my talent Blood Craze (3% health regened over 6sec after being the victim of a critical strike : 3 ticks of 1% health) is healing for 4 times as much as it should, I have contacted a GM who told me that I should post the issue here.
I've attached a screenchot in which you can see the health that I'm gaining back from the talent.
Please note that it was working fine yesterday and before that.
Thank you for your time :)
![bug_blood_craze_times4](https://user-images.githubusercontent.com/39851881/40872341-0597f8b8-664d-11e8-99d7-cd2eac7aacdd.png)

**Comment by Thenari** [comment]
Haha. I was told it was fixed and i should test it soon. Guess you tested it for me ;P

**Comment by drozdez** [comment]
I fixed it now, sorry for forgetting to fix the first rank :D

**Comment by Destard** [comment]
This bug is still occurring. I'm getting back 12% of my hp over 6 seconds instead of 3%. It's ticking 4% of my hp every 2 seconds.
![capture](https://user-images.githubusercontent.com/43377292/49963285-81982d80-fee5-11e8-8691-5ed538b672ef.PNG)
